from typing import Any

from technitium_dns_mcp.api.api_client_base import ApiClientBase


class ApiClientUser(ApiClientBase):
    def get_sso_status(self) -> dict[str, Any]:
        """Gets SSO status of the server."""
        return self.request("GET", "/api/sso/status")

    def login(
        self,
        user: str,
        password: str,
        totp: str | None = None,
        include_info: bool | None = None,
    ) -> dict[str, Any]:
        """Log in to the DNS server to obtain a session token.

        Args:
            user: Username.
            password: Password.
            totp: Time-based One-Time Password (optional).
            include_info: Include extra user details in response (optional).
        """
        data = {"user": user, "pass": password}
        if totp is not None:
            data["totp"] = totp
        if include_info is not None:
            data["includeInfo"] = str(include_info).lower()
        return self.request("POST", "/api/user/login", data=data)

    def create_token(
        self,
        user: str,
        password: str,
        token_name: str,
        totp: str | None = None,
    ) -> dict[str, Any]:
        """Creates an API token for long-term programmatic access.

        Args:
            user: Username.
            password: Password.
            token_name: Name of the token.
            totp: Time-based One-Time Password (optional).
        """
        data = {"user": user, "pass": password, "tokenName": token_name}
        if totp is not None:
            data["totp"] = totp
        return self.request("POST", "/api/user/createToken", data=data)

    def create_single_use_token(self) -> dict[str, Any]:
        """Creates a single-use token."""
        return self.request("POST", "/api/user/createSingleUseToken")

    def logout(self) -> dict[str, Any]:
        """Logs out the current session."""
        return self.request("POST", "/api/user/logout")

    def get_session_info(self) -> dict[str, Any]:
        """Gets info about the current session."""
        return self.request("GET", "/api/user/session/get")

    def delete_user_session(self, partial_token: str) -> dict[str, Any]:
        """Deletes a specific user session token.

        Args:
            partial_token: The partial token identifier.
        """
        data = {"partialToken": partial_token}
        return self.request("POST", "/api/user/session/delete", data=data)

    def change_password(
        self,
        password: str,
        new_password: str,
        totp: str | None = None,
        iterations: int | None = None,
    ) -> dict[str, Any]:
        """Changes password for the current user session.

        Args:
            password: Current password.
            new_password: New password.
            totp: 2FA OTP code if enabled (optional).
            iterations: Iterations count for hash generation (optional).
        """
        data = {"pass": password, "newPass": new_password}
        if totp is not None:
            data["totp"] = totp
        if iterations is not None:
            data["iterations"] = str(iterations)
        return self.request("POST", "/api/user/changePassword", data=data)

    def initialize_2fa(self) -> dict[str, Any]:
        """Initializes Time-based One-Time Password setup."""
        return self.request("POST", "/api/user/2fa/init")

    def enable_2fa(self, totp: str) -> dict[str, Any]:
        """Enables 2FA with the provided TOTP code.

        Args:
            totp: The code generated by the authenticator app.
        """
        data = {"totp": totp}
        return self.request("POST", "/api/user/2fa/enable", data=data)

    def disable_2fa(self) -> dict[str, Any]:
        """Disables 2FA for the current user."""
        return self.request("POST", "/api/user/2fa/disable")

    def get_user_profile_details(self) -> dict[str, Any]:
        """Retrieves user profile details."""
        return self.request("GET", "/api/user/profile/get")

    def set_user_profile_details(
        self,
        display_name: str | None = None,
        session_timeout_seconds: int | None = None,
    ) -> dict[str, Any]:
        """Updates user profile settings.

        Args:
            display_name: The display name to set (optional).
            session_timeout_seconds: Auto logout timeout in seconds (optional).
        """
        data = {}
        if display_name is not None:
            data["displayName"] = display_name
        if session_timeout_seconds is not None:
            data["sessionTimeoutSeconds"] = str(session_timeout_seconds)
        return self.request("POST", "/api/user/profile/set", data=data)

    def check_for_update(self) -> dict[str, Any]:
        """Checks for software updates."""
        return self.request("GET", "/api/user/checkForUpdate")
